### ISSUE TITLE
Error running application.

### ISSUE THREAD

**Issue by cletisgipson** [Azure-Samples/azure-cosmos-db-dotnet-graphexplorer#12]
I just updated the appsettings.json with the correct information for my instance. I published it to a azure web app and I get the following error.

`
vendor.js:12885 Unhandled rejection Error: Cannot find module './aurelia-templating-resources/if.html'.
    at webpackContextResolve (http://doedependency.azurewebsites.net/wwwroot/dist/app.js?ver=1.0.6484.16090:428:9)
    at webpackContext (http://doedependency.azurewebsites.net/wwwroot/dist/app.js?ver=1.0.6484.16090:423:29)
    at http://doedependency.azurewebsites.net/wwwroot/dist/app.js?ver=1.0.6484.16090:3872:47
From previous event:
    at Promise.then._this2.modulesBeingLoaded.(anonymous function) (http://doedependency.azurewebsites.net/wwwroot/dist/app.js?ver=1.0.6484.16090:3871:81)
From previous event:
    at WebpackLoader._import (http://doedependency.azurewebsites.net/wwwroot/dist/app.js?ver=1.0.6484.16090:3857:18)
    at WebpackLoader.loadTemplate (http://doedependency.azurewebsites.net/wwwroot/dist/app.js?ver=1.0.6484.16090:3921:17)
    at ensureRegistryEntry (http://doedependency.azurewebsites.net/wwwroot/dist/vendor.js:3290:17)
    at ViewEngine.loadViewFactory (http://doedependency.azurewebsites.net/wwwroot/dist/vendor.js:3358:12)
    at ConventionalViewStrategy.loadViewFactory (http://doedependency.azurewebsites.net/wwwroot/dist/vendor.js:748:23)
    at HtmlBehaviorResource.load (http://doedependency.azurewebsites.net/wwwroot/dist/vendor.js:4137:27)
    at ResourceDescription.load (http://doedependency.azurewebsites.net/wwwroot/dist/vendor.js:3177:26)
    at ResourceModule.load (http://doedependency.azurewebsites.net/wwwroot/dist/vendor.js:3119:23)
    at http://doedependency.azurewebsites.net/wwwroot/dist/vendor.js:3489:41
From previous event:
    at ViewEngine.importViewResources (http://doedependency.azurewebsites.net/wwwroot/dist/vendor.js:3458:50)
    at http://doedependency.azurewebsites.net/wwwroot/dist/vendor.js:32433:23
From previous event:
    at loadResources (http://doedependency.azurewebsites.net/wwwroot/dist/vendor.js:32424:7)
    at http://doedependency.azurewebsites.net/wwwroot/dist/vendor.js:32501:14
    at next (http://doedependency.azurewebsites.net/wwwroot/dist/vendor.js:32381:30)
    at runTasks (http://doedependency.azurewebsites.net/wwwroot/dist/vendor.js:32387:10)
    at http://doedependency.azurewebsites.net/wwwroot/dist/vendor.js:32667:16
From previous event:
    at http://doedependency.azurewebsites.net/wwwroot/dist/vendor.js:32666:21
From previous event:
    at FrameworkConfiguration.apply (http://doedependency.azurewebsites.net/wwwroot/dist/vendor.js:32651:42)
    at Aurelia.start (http://doedependency.azurewebsites.net/wwwroot/dist/vendor.js:32267:37)
    at Object.configure (http://doedependency.azurewebsites.net/wwwroot/dist/app.js?ver=1.0.6484.16090:3999:13)
    at http://doedependency.azurewebsites.net/wwwroot/dist/app.js?ver=1.0.6484.16090:3682:27
From previous event:
    at config (http://doedependency.azurewebsites.net/wwwroot/dist/app.js?ver=1.0.6484.16090:3681:46)
    at handleApp (http://doedependency.azurewebsites.net/wwwroot/dist/app.js?ver=1.0.6484.16090:3672:10)
    at http://doedependency.azurewebsites.net/wwwroot/dist/app.js?ver=1.0.6484.16090:3700:9
From previous event:
    at http://doedependency.azurewebsites.net/wwwroot/dist/app.js?ver=1.0.6484.16090:3697:44
From previous event:
    at run (http://doedependency.azurewebsites.net/wwwroot/dist/app.js?ver=1.0.6484.16090:3694:24)
    at Object.<anonymous> (http://doedependency.azurewebsites.net/wwwroot/dist/app.js?ver=1.0.6484.16090:3719:1)
    at Object.aurelia-bootstrapper-webpack (http://doedependency.azurewebsites.net/wwwroot/dist/app.js?ver=1.0.6484.16090:3720:30)
    at __webpack_require__ (http://doedependency.azurewebsites.net/wwwroot/dist/app.js?ver=1.0.6484.16090:24:38)
    at 0 (http://doedependency.azurewebsites.net/wwwroot/dist/app.js?ver=1.0.6484.16090:66:18)
    at http://doedependency.azurewebsites.net/wwwroot/dist/app.js?ver=1.0.6484.16090:69:10`

Any suggestions on how to fix this?

**Comment by vhilliard** [comment]
I found that publishing to Azure through VS would not publish all files properly, especially the wwwroot folder containing the webpack modules. You could try what I did, by publishing offline and copying over the PublishOutput to the Azure Web App, e.g. through configuring the FTP credentials in Azure.

**Comment by sachsie** [comment]
vhilliards tip solved my problem (at least one of them): I changed the publish mode in Visual Studio to FTP-upload. The regular deployment option didn't upload the dist-folder. As a result, the permanent "Loading…"-screen appears and the explorer did not load. 

The best way to set up FTP-upload is to look up the credentials in the publishing settings-file. You will find it in the top right corner of your apps home screen.

**Comment by mike7502** [comment]
> 
> 
> Is this still happening?

@alexdrenea This is still happening! 

I tried the workaround from @sachsie to publish using FTP etc but the "Loading error" does not go away! I tried several ways to publish via FTP and checked that files were getting uploaded correctly.

I have verified everything else in this and other threads under "issues" section reported for this app - webpack, aurelia, nodejs etc and made sure the test app to upload test data also publishes correctly. Been at it for last 6 hours.

I have verified that there are no errors while building through VS2017

The error all along (even prior to publishing using FTP etc) has been regarding a missing vendor.js and app.js - it seems to be looking in the wrong folder hierarchy perhaps - as in attached screenshot. Am unable to find those js files

![image](https://user-images.githubusercontent.com/44972547/48350651-bdb54580-e63c-11e8-8a2b-6add31ce703e.png)

@vhilliard - would you happen to remember which is the publishoutput folder you used in your workaround of _"..copying over the PublishOutput to the Azure Web App"_ - i am only publishing to site/wwwroot - it that good enough?

![image](https://user-images.githubusercontent.com/44972547/48351046-dd00a280-e63d-11e8-85a7-5dd65325b531.png)

thank you!
